$ANSIBLE_VAULT;1.1;AES256
64636132633137653365646435616135313063346566326435356663626331353263663635613239
3865643838346330653064353535626134663534373531370a316335656265336635303964613461
33613861633261346436396466303465323330373130323465336530356563323065663630643663
3430326562313665340a613037316266663364316337396430356237373964323036306566623264
62316334353033623937313738313934376132303066306131633737633130646330393665326163
33643661663536336332393530613638343433383131343965383763633437653835643231306263
37316337383334623437376630346236666534623032366464643030316465336230396261636337
62336561613432376466313639323633343837326663316335643834613433623461326336303862
32656365353231373734393931646263316431383039393331613461636139323361383431613430
6536613436376661396362333663633336653964306165313535
