- name: install nginx and start the service
  hosts: frontend
  become: yes
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Download the front content
      get_url: 
        url: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip    
        dest: /tmp/frontend.zip

    - name: Remove old nginx content
      file: 
        path: /usr/share/nginx/html
        state: absent

    - name: recreate nginx html directory
      file:
        path: /usr/share/nginx/html
        state: directory

    - name:  Install unzip package
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Unzip the frontend content
      unarchive:
        src: /tmp/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: ensure nginx is running
      service:
        name: nginx
        state: started
        enabled: yes     
    